schema_version = "1.0.0"

id = "advanced_ascii_art_generator"
version = "1.1.2"
name = "Advanced ASCII Art Generator"
tagline = "Convert 3D scenes to customizable ASCII art"
maintainer = "reinterpret_cast"
type = "add-on"

website = "https://t.me/telllmewhatt"
tags = ["Render", "ASCII", "Art", "Converter"]
blender_version_min = "4.5.0"

license = [
    "GPL-3.0-or-later",
]

copyright = [
    "2025",
]

[permissions]
files = "Read/write ASCII art output files to disk"